# Generated by Django 2.0 on 2017-12-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_rgs_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioscience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=150)),
                ('ca', models.CharField(max_length=150)),
                ('rg', models.CharField(max_length=150)),
            ],
        ),
    ]
