# Generated by Django 2.0 on 2017-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_bioscience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_results', models.CharField(max_length=150)),
                ('enterprise', models.CharField(max_length=150)),
                ('operating_unit', models.CharField(max_length=150)),
                ('ca', models.CharField(max_length=150)),
                ('rg', models.CharField(max_length=150)),
                ('respondent', models.CharField(max_length=150)),
                ('respondent_title', models.CharField(max_length=150)),
                ('capability_status', models.CharField(max_length=150)),
                ('people', models.CharField(max_length=150)),
                ('tools', models.CharField(max_length=150)),
                ('processes', models.CharField(max_length=150)),
                ('equipment', models.CharField(max_length=150)),
                ('facilities', models.CharField(max_length=150)),
                ('supplies', models.CharField(max_length=150)),
                ('catalogue', models.CharField(max_length=150)),
                ('capability_group', models.CharField(max_length=150)),
                ('capability_subgroup', models.CharField(max_length=150)),
                ('capability', models.CharField(max_length=150)),
                ('Capability_Status_rank', models.PositiveIntegerField()),
                ('People_avg', models.PositiveIntegerField()),
                ('Tools_avg', models.PositiveIntegerField()),
                ('Processes_avg', models.PositiveIntegerField()),
                ('Equipment_avg', models.PositiveIntegerField()),
                ('Facilities_avg', models.PositiveIntegerField()),
                ('Supplies_avg', models.PositiveIntegerField()),
                ('average', models.PositiveIntegerField()),
            ],
        ),
    ]
