# Generated by Django 2.0 on 2017-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='Capability_Status_rank',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Equipment_avg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Facilities_avg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='People_avg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Processes_avg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Supplies_avg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Tools_avg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bio',
            name='average',
            field=models.CharField(max_length=150),
        ),
    ]
